config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  apipie
  # root to: 'apipie/apipies#index'
  root to: 'dashboard#index'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  resources :roles
  resources :users, only:[:index, :edit, :destroy] do
    member do
      patch 'update_user'
    end
  end
  
  resources :companies

  namespace :api do
    namespace :v1 do
      resources :registrations, only: [] do
        collection do
          post :sign_up
          # post :sing_up_social_media
          post :forgot_password
        end
      end
      
      resources :user_sessions do
        collection do
          post :sign_in
        end
      end

      resources :companies, only: [:index, :show]
      
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  include ResponseBuilder
  
  
  has_many :user_sessions, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :email, presence: true
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  def self.sign_up(data)
    data = HashWithIndifferentAccess.new(data)
    
    user            = User.new
    user.attributes = data[:user]
    status, message = validate_email_and_password(data)
    if !status.present?
      if user.save
        user.add_role(AppConstants::APP_USER)
        # User.send_email(member_profile.user.email)
        resp_data    = {}
        resp_status  = 1
        resp_message = 'You\'re successfully signed up.'
        resp_errors  = ''
      else
        resp_data    = {}
        resp_status  = 0
        resp_message = 'Errors'
        resp_errors  = error_messages(user)
      end
    else
      resp_data    = {}
      resp_status  = 0
      resp_message = 'error'
      resp_errors  = message
    end
    
    
    ResponseBuilder.json_builder(resp_data, resp_status, resp_message, errors: resp_errors)
  end
  
  def self.sign_in(data)
    data = HashWithIndifferentAccess.new(data)
    
    if data[:user][:email].present?
      user = User.find_by_email(data[:user][:email])
    end
    
    if user && user.valid_password?(data[:user][:password])
      if !user.is_deleted
        user_sessions = UserSession.where("device_uuid = ? AND user_id != ?", data[:user_session][:device_uuid], user.id)
        user_sessions.destroy_all if user_sessions.present?
        user_session                = user.user_sessions.where(device_uuid: data[:user_session][:device_uuid]).try(:first) || user.user_sessions.build(data[:user_session])
        user_session.auth_token     = SecureRandom.hex(100)
        user_session.session_status = 'open'
        user_session.save(validate: false)
        
        response    = user.as_json(
                     only:[:id, :username, :email]
        ).merge!(auth_token: user_session.auth_token).as_json

        resp_data    = {user: response}
        resp_status  = 1
        resp_message = 'User Logged In successful.'
        resp_errors  = ''
      else
        resp_data    = {}
        resp_status  = 1
        resp_message = 'Attention.'
        resp_errors  = 'Your account is blocked. Please contact with admin.'
      end
    else
      resp_data    = {}
      resp_status  = 0
      resp_message = 'Errors'
      resp_errors  = 'Either your email or password is incorrect'
    end
    
    ResponseBuilder.json_builder(resp_data, resp_status, resp_message, errors: resp_errors)
  end
  
  def self.validate_email_and_password(data)
    status  = false
    message = ''
    if data[:user][:password] != data[:user][:password_confirmation]
      message = "Password mismatch."
      status  = true
    end
    [status, message]
  end
  
  def self.error_messages(error_array)
    error_string = ''
    error_array.errors.full_messages.each do |message|
      error_string += message + ', '
    end
    error_string
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string(255)
#  last_name              :string(255)
#  phone                  :string(255)
#  parent_id              :integer
#  commission             :float(24)
#  limit_amount           :float(24)        default(0.0)
#  amount_used            :float(24)        default(0.0)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    if @current_user_role == AppConstants::SUPER_ADMIN
      @users = User.all
    elsif @current_user_role == AppConstants::RESTAURANT
      @users = User.where(restaurant_id: current_user.restaurant_id)
    end
  end
  
  # def edit
  #   @user = User.find(params[:id])
  # end
  #
  # def update_user
  #   @user = User.find_by_id(params[:id])
  #   if @user.update(update_user_params)
  #     flash[:success] = 'User successfully updated.'
  #     redirect_to root_url
  #   else
  #     flash[:danger] = 'User already exist'
  #     redirect_to :back
  #   end
  # end
  
  def destroy
    if @user.present?
      if @user.is_deleted?
        @user.is_deleted = false
      else
        @user.is_deleted = true
      end
      @user.save(validate: false)
    end

    redirect_to users_path, notice: 'User was successfully destroyed.'
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation, :restaurant_branch_id)
  end
  
  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation, :restaurant_branch_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user, url: url ) do |f|
  = f.error_notification
  = f.input :first_name, autofocus: true
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.input :phone
  - if @current_user_role == AppConstants::SUPER_ADMIN
    = f.input :restaurant_branch_id, collection: RestaurantBranch.all.map { |r| ["#{r.try(:restaurant).try(:restaurant_name)}, #{r.street}", r.id] }, prompt: 'Select Restaurant'
  - elsif @current_user_role == AppConstants::RESTAURANT
    = f.input :restaurant_branch_id, as: :hidden, input_html: {value: current_user.restaurant_branch_id}
  .form-actions
    = link_to 'Cancel', users_path, class: 'btn btn-default'
    = f.submit 'Save', class: 'btn btn-primary'

app/views/users/edit.html.haml
.x_panel
  .x_title
    %h2 Add User
    .clearfix
  .x_content
    %div.row
      .col-md-6
        = render 'form', user: @user, url: update_user_user_path(@user)

app/views/users/index.html.haml
.x_panel
  .x_title
    %h2 Users
    .clearfix
  .x_content
    %table.table.table-striped.table-hover.listing_table
      %thead
        %tr
          %th Username
          %th Email
          %th Phone
          %th Actions
      %tbody
        - @users&.each do |user|
          %tr
            %td= user.username
            %td= user.email
            %td= user.phone
            %td
              - if user.is_deleted?
                = link_to 'Undo', user, method: :delete, data: { confirm: 'Are you sure?' }
              - else
                = link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }