config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  apipie
  # root to: 'apipie/apipies#index'
  root to: 'dashboard#index'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  resources :roles
  resources :users, only:[:index, :edit, :destroy] do
    member do
      patch 'update_user'
    end
  end
  
  resources :companies

  namespace :api do
    namespace :v1 do
      resources :registrations, only: [] do
        collection do
          post :sign_up
          # post :sing_up_social_media
          post :forgot_password
        end
      end
      
      resources :user_sessions do
        collection do
          post :sign_in
        end
      end

      resources :companies, only: [:index, :show]
      
    end
  end

end

app/models/company.rb
class Company < ApplicationRecord
  include ResponseBuilder
  
  has_many :company_addresses
  has_many :company_galleries
  
  accepts_nested_attributes_for :company_addresses, :company_galleries, allow_destroy: true
  
  mount_uploader :company_logo, ImageUploader
  
  validates :company_name, presence: true
  
  scope :active, -> { where(is_active: true) }
  
  def self.api_company_listing(data)
    begin
      per_page = (data[:per_page] || 20).to_i
      page     = (data[:page] || 1).to_i
      
      companies = Company.all
      companies = companies.page(page.to_i).per_page(per_page.to_i)
      
      paging_data = ResponseBuilder.get_paging_data(page, per_page, companies)
      companies   = companies.as_json(
          only: [:id, :company_name, :company_logo, :short_description, :is_seen]
      )
      
      resp_data    = { companies: companies }.as_json
      resp_status  = 1
      resp_message = 'Companies List'
      resp_errors  = ''
    rescue Exception => e
      resp_data    = {}
      resp_status  = 0
      paging_data  = ''
      resp_message = 'error'
      resp_errors  = e
    end
    ResponseBuilder.json_builder(resp_data, resp_status, resp_message, errors: resp_errors, paging_data: paging_data)
  end
  
  def self.api_company_details(data)
    begin
      company = Company.where(id: data[:id])
      if company.present?
        
        company = company.as_json(
            only: [:id, :company_name, :company_logo, :short_description, :is_seen],
            include:{
                company_addresses: {
                    only: [:id, :street, :cit, :state, :zip]
                }
            }
        )
        
        resp_data    = { companies: company }.as_json
        resp_status  = 1
        resp_message = 'Companies Details'
        resp_errors  = ''
      else
        resp_data    = {}
        resp_status  = 1
        resp_message = 'No company found.'
        resp_errors  = ''
      end
    rescue Exception => e
      resp_data    = {}
      resp_status  = 0
      resp_message = 'error'
      resp_errors  = e
    end
    ResponseBuilder.json_builder(resp_data, resp_status, resp_message, errors: resp_errors)
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < ActionController::Base
  
  api :GET, '/v1/companies.json', "Company List"
  formats ['json', 'xml']
  example <<-EOS
        Request:
        {
          "auth_token": "XXXXXXXX",
          "page": 1,
          "per_page": 20 
        }

        Response:
        {
          "resp_status":1,
          "message":"Companies List",
          "errors":"",
          "paging_data":{
            "page":1,
            "per_page":1,
            "total_records":2,
            "total_pages":2,
            "next_page_exist": true/false,
            "previous_page_exist": true/false
          },
          "data":{
            "companies":[
              {
                "id": xx,
                "company_name":"XXX",
                "company_logo":{
                  "url": "URL"
                },
                "short_description":"XXXXx",
                "is_seen": true/false
              }
            ]
          }
        }
  EOS
  
  param :auth_token, String, desc: 'Auth Token', required: true
  param :page, Integer, desc: 'Page', required: false
  param :per_page, Integer, desc: 'Per Page', required: false
  
  def index
    user_session = UserSession.find_by_auth_token(params[:auth_token])
    if user_session.present?
      resp_data = Company.api_company_listing(params)
      render json: resp_data
    else
      resp_data = { resp_status: 0, message: 'Invalid Token', error: '', data: {} }
      return render json: resp_data
    end
  end
  
  api :GET, '/v1/companies/{ID}.json', "Company Details"
  formats ['json', 'xml']
  example <<-EOS
        Request:
        {
          "auth_token": "XXXXXXXX",
          "id": 1 
        }

        Response:
        {
          "resp_status":1,
          "message":"Companies Details",
          "errors":"",
          "paging_data":null,
          "data":{
            "companies":[
              {
                "id":1,
                "company_name": "XXX",
                "company_logo":{
                  "url": "URL"
                },
                "short_description": "XXX",
                "is_seen": true/false,
                "company_addresses":[
                  {
                    "id": xx,
                    "street": "XXX",
                    "state": "XXX",
                    "zip": "XXx"
                  }
                ]
              }
            ]
          }
        }
  EOS
  
  param :auth_token, String, desc: 'Auth Token', required: true
  param :id, String, desc: 'Company Id', required: true
  
  def show
    user_session = UserSession.find_by_auth_token(params[:auth_token])
    if user_session.present?
      resp_data = Company.api_company_details(params)
      render json: resp_data
    else
      resp_data = { resp_status: 0, message: 'Invalid Token', error: '', data: {} }
      return render json: resp_data
    end
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  
  def index
    @companies = Company.all
  end
  
  def show
    @company_addresses = @company.company_addresses
  end
  
  def new
    @company = Company.new
    1.times { @company.company_addresses.build }
  end

  def create
    @company = Company.new(company_params)
  
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    if @company.present?
      if @company.is_active?
        @company.is_active = false
      else
        @company.is_active = true
      end
      @company.save
    end
    
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end
  
    def company_params
      params.require(:company).permit(:company_name, :company_logo, :short_description, :description, :is_seen, :is_active, company_addresses_attributes: [:street, :city, :state, :zip])
    end
end

app/helpers/api/v1/companies_helper.rb
module Api::V1::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company_address_fields.html.haml
.nested-fields
  .panel.panel-default
    .panel-heading
      %strong Company Address
    .panel-body
      .col-md-3
        = f.input :street, placeholder: 'Street', label: false
      .col-md-3
        = f.input :city, placeholder: 'city', label: false
      .col-md-3
        = f.input :state, placeholder: 'State', label: false
      .col-md-3
        = f.input :zip,placeholder: 'Zip', label: false
    = link_to_remove_association 'x', f, class: 'btn btn-sm btn-danger'

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification
  .form-inputs
    = f.input :company_name
    = f.input :company_logo, as: :file, :label => 'Choose company logo'
    = f.input :short_description, placeholder: 'Enter short description'
    = f.input :description, placeholder: 'Enter long description'
    = f.input :is_seen
    = f.input :is_active

    = f.simple_fields_for :company_addresses do |company_address|
      = render 'company_address_fields', f: company_address

    .links
      = link_to_add_association 'Add More Addresses', f, :company_addresses, class: 'btn btn-info'
  .form-actions
    = link_to 'Back', companies_path, class: 'btn btn-default'
    = f.submit 'Save', class: 'btn btn-primary'

app/views/companies/edit.html.haml
.x_panel
  .x_title
    %h1 Editing Company
    .clearfix
  .x_content
    = render 'form', company: @company

app/views/companies/index.html.haml
.x_panel
  .x_title
    .row
      .col-md-6
        %h2 Companies
      .col-md-6
        = link_to 'New Company', new_company_path, class: 'btn btn-primary pull-right'
    .clearfix
  .x_content
    %table.table.table-striped.table-hover.listing_table
      %thead
        %tr
          %th Company name
          %th Is seen
          %th Is active
          %th Actions
      %tbody
        - @companies&.each do |company|
          %tr
            %td= company.company_name
            %td= company.is_seen
            %td= company.is_active
            %td
              = link_to 'Show', company
              |
              = link_to 'Edit', edit_company_path(company)
              |
              - if company.is_active?
                = link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }
              - else
                = link_to 'Undo', company, method: :delete, data: { confirm: 'Are you sure?' }

app/views/companies/new.html.haml
.x_panel
  .x_title
    %h1 New Company
    .clearfix
  .x_content
    = render 'form', company: @company

app/views/companies/show.html.haml
%p#notice= notice
%p
  %strong.col-md-4 Company name:
  = @company.company_name
%p
  %strong.col-md-4 Company logo:
  - if @company.company_logo?
    = link_to image_tag(@company.company_logo.url,:size => "160x100"), @company.company_logo.url, target: :_blank
  - else
    No Logo found
%p
  %strong.col-md-4 Short description:
  = @company.short_description
%p
  %strong.col-md-4 Description:
  = @company.description
%p
  %strong.col-md-4 Is seen:
  = @company.is_seen
%p
  %strong.col-md-4 Is active:
  = @company.is_active
%p
  .panel.panel-default
    .panel-heading
      %strong Company Addresses
    .panel-body
      %table.table.table-striped.table-hover.listing_table
        %thead
          %tr
            %th Street
            %th City
            %th State
            %th Zip
        %tbody
          - @company_addresses.each do |company_address|
            %tr
              %td= company_address.street
              %td= company_address.city
              %td= company_address.state
              %td= company_address.zip

= link_to 'Edit', edit_company_path(@company)
|
= link_to 'Back', companies_path