config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  apipie
  # root to: 'apipie/apipies#index'
  root to: 'dashboard#index'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  resources :roles
  resources :users, only:[:index, :edit, :destroy] do
    member do
      patch 'update_user'
    end
  end
  
  resources :companies

  namespace :api do
    namespace :v1 do
      resources :registrations, only: [] do
        collection do
          post :sign_up
          # post :sing_up_social_media
          post :forgot_password
        end
      end
      
      resources :user_sessions do
        collection do
          post :sign_in
        end
      end

      resources :companies, only: [:index, :show]
      
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, success: 'Role was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, success: 'Role was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, success: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name)
    end
end
 

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= simple_form_for(@role) do |f|
  = f.error_notification
  .form-inputs.row
    .col-md-4
      %fieldset.fieldset-border
        - if @role.new_record?
          %legend.fieldset-border New Role
        - else
          %legend.fieldset-border Edit Role
        = f.input :name
        .form-actions
          = link_to 'Back', roles_path, class: 'btn btn-default'
          = f.button :submit, class: 'btn btn-primary'

app/views/roles/edit.html.haml
= render 'form', role: @role

app/views/roles/index.html.haml
%h1 Roles
= link_to 'New Role', new_role_path, class: 'btn btn-primary pull-right'
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Actions
  %tbody
    - @roles.each do |role|
      %tr
        %td= role.name
        %td
          = link_to 'Edit', edit_role_path(role), class: 'btn btn-sm btn-primary'
          = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
%br/

app/views/roles/new.html.haml
= render 'form', role: @role

app/views/roles/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @role.name
= link_to 'Edit', edit_role_path(@role)
|
= link_to 'Back', roles_path